### ISSUE TITLE
Filter connections with warnings?

### ISSUE THREAD

**Issue by flopezo** [mourisl/Rascaf#10]
Hello,

I'm using Rascaf with sorted BAM files from HISAT2 alignments of multiple stranded RNA-Seq libraries. In each of the Rascaf .out files, there are several connections below the section 'WARNINGS:'. I was wondering if it's necessary to remove those lines from the .out files before using `rascaf-join`. Or perhaps run Rascaf with the `-cs` flag, use the '_cs.fa' files to search with BLASTN/BLASTX against RefSeq RNA or NR, and then run the `FilterRascafConnection.pl` script?

Any help is greatly appreciated.

**Comment by mourisl** [comment]
The connections below WARNINGS are ignored in rascaf_join, it just reports some ambiguous extension if someone is interested in looking at them. 

If you like the extreme trustworthy connections, you can use BLASTN to only use the connections valided by the genes in the database.

Does this help?

Li

**Comment by flopezo** [comment]
Yes, that helps. Thank you!
