### ISSUE TITLE
invalid pointer error

### ISSUE THREAD

**Issue by lijingbu** [mourisl/Rascaf#11]
Dear Rascaf Developer,

I got error messages when running the command below. Does that have anything to do with the fact I am using /dev/shm to store some data?  I compiled the lasted version but still get issues. 

Thanks for your time! 

> ./rascaf -b bwa_bh_C1_S7/sorted.mapM_PE_bh_C1_S7.bam -f k63_127.scafSeq -o rascaf_bh_C1_S7
> *** Error in `/my/path/local_projects/software/rascaf/rascaf': munmap_chunk(): invalid pointer: 0x0000000004727be0 ***
> ======= Backtrace: =========
> /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff3cc6777e5]
> /lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7ff3cc684698]
> /my/path/local_projects/software/Rascaf-master/rascaf[0x406a93]
> /my/path/local_projects/software/Rascaf-master/rascaf[0x40e6ea]
> /my/path/local_projects/software/Rascaf-master/rascaf[0x403561]
> /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ff3cc620830]
> /my/path/local_projects/software/Rascaf-master/rascaf[0x4041b9]
> ======= Memory map: ========
> 00400000-00435000 r-xp 00000000 00:2c 347975645                          /my/path/local_projects/software/Rascaf-master/rascaf
> 00634000-00635000 r--p 00034000 00:2c 347975645                          /my/path/local_projects/software/Rascaf-master/rascaf
> 00635000-00636000 rw-p 00035000 00:2c 347975645                          /my/path/local_projects/software/Rascaf-master/rascaf
> 01408000-04733000 rw-p 00000000 00:00 0                                  [heap]
> 7ff3cb851000-7ff3cc600000 rw-p 00000000 00:00 0
> 7ff3cc600000-7ff3cc7c0000 r-xp 00000000 08:03 12321415                   /lib/x86_64-linux-gnu/libc-2.23.so
> 7ff3cc7c0000-7ff3cc9c0000 ---p 001c0000 08:03 12321415                   /lib/x86_64-linux-gnu/libc-2.23.so
> 7ff3cc9c0000-7ff3cc9c4000 r--p 001c0000 08:03 12321415                   /lib/x86_64-linux-gnu/libc-2.23.so
> 7ff3cc9c4000-7ff3cc9c6000 rw-p 001c4000 08:03 12321415                   /lib/x86_64-linux-gnu/libc-2.23.so
> 7ff3cc9c6000-7ff3cc9ca000 rw-p 00000000 00:00 0
> 7ff3cc9ca000-7ff3cc9e0000 r-xp 00000000 08:03 12320962                   /lib/x86_64-linux-gnu/libgcc_s.so.1
> 7ff3cc9e0000-7ff3ccbdf000 ---p 00016000 08:03 12320962                   /lib/x86_64-linux-gnu/libgcc_s.so.1
> 7ff3ccbdf000-7ff3ccbe0000 rw-p 00015000 08:03 12320962                   /lib/x86_64-linux-gnu/libgcc_s.so.1
> 7ff3ccbe0000-7ff3ccce8000 r-xp 00000000 08:03 12321044                   /lib/x86_64-linux-gnu/libm-2.23.so
> 7ff3ccce8000-7ff3ccee7000 ---p 00108000 08:03 12321044                   /lib/x86_64-linux-gnu/libm-2.23.so
> 7ff3ccee7000-7ff3ccee8000 r--p 00107000 08:03 12321044                   /lib/x86_64-linux-gnu/libm-2.23.so
> 7ff3ccee8000-7ff3ccee9000 rw-p 00108000 08:03 12321044                   /lib/x86_64-linux-gnu/libm-2.23.so
> 7ff3ccee9000-7ff3cd05b000 r-xp 00000000 08:03 2884841                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
> 7ff3cd05b000-7ff3cd25b000 ---p 00172000 08:03 2884841                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
> 7ff3cd25b000-7ff3cd265000 r--p 00172000 08:03 2884841                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
> 7ff3cd265000-7ff3cd267000 rw-p 0017c000 08:03 2884841                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
> 7ff3cd267000-7ff3cd26b000 rw-p 00000000 00:00 0
> 7ff3cd26b000-7ff3cd283000 r-xp 00000000 08:03 12320927                   /lib/x86_64-linux-gnu/libpthread-2.23.so
> 7ff3cd283000-7ff3cd482000 ---p 00018000 08:03 12320927                   /lib/x86_64-linux-gnu/libpthread-2.23.so
> 7ff3cd482000-7ff3cd483000 r--p 00017000 08:03 12320927                   /lib/x86_64-linux-gnu/libpthread-2.23.so
> 7ff3cd483000-7ff3cd484000 rw-p 00018000 08:03 12320927                   /lib/x86_64-linux-gnu/libpthread-2.23.so
> 7ff3cd484000-7ff3cd488000 rw-p 00000000 00:00 0
> 7ff3cd488000-7ff3cd4a1000 r-xp 00000000 00:2d 73183823118                /users/lijing/usr/lib/libz.so.1.2.8
> 7ff3cd4a1000-7ff3cd6a0000 ---p 00019000 00:2d 73183823118                /users/lijing/usr/lib/libz.so.1.2.8
> 7ff3cd6a0000-7ff3cd6a1000 r--p 00018000 00:2d 73183823118                /users/lijing/usr/lib/libz.so.1.2.8
> 7ff3cd6a1000-7ff3cd6a2000 rw-p 00019000 00:2d 73183823118                /users/lijing/usr/lib/libz.so.1.2.8
> 7ff3cd6a2000-7ff3cd6c8000 r-xp 00000000 08:03 12320852                   /lib/x86_64-linux-gnu/ld-2.23.so
> 7ff3cd6df000-7ff3cd8b7000 rw-p 00000000 00:00 0
> 7ff3cd8c4000-7ff3cd8c7000 rw-p 00000000 00:00 0
> 7ff3cd8c7000-7ff3cd8c8000 r--p 00025000 08:03 12320852                   /lib/x86_64-linux-gnu/ld-2.23.so
> 7ff3cd8c8000-7ff3cd8c9000 rw-p 00026000 08:03 12320852                   /lib/x86_64-linux-gnu/ld-2.23.so
> 7ff3cd8c9000-7ff3cd8ca000 rw-p 00000000 00:00 0
> 7ffffe8ce000-7ffffe8f0000 rw-p 00000000 00:00 0                          [stack]
> 7ffffe9e3000-7ffffe9e5000 r--p 00000000 00:00 0                          [vvar]
> 7ffffe9e5000-7ffffe9e7000 r-xp 00000000 00:00 0                          [vdso]
> ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
> Aborted (core dumped)

**Comment by lijingbu** [comment]
Thanks for the prompt response. 
Looks the -v error message is identical to the command before.

I tried on another server which doesn't have anything in /dev/shm, it gives the same error message. 
Although, the command runs correctly on the test sample data. 
Maybe unlikely, but could that because of too large bam file? This bam file is 2.6GB. And the contigs numbers are 20k.

**Comment by mourisl** [comment]
Could you please show me the last few lines for rascaf_bh_C1_S7.out file generated by rascaf so I can pin point at which stage it crashed? Thanks.

**Comment by lijingbu** [comment]
Ah, I found out where the issue is: I pointed -f to a wrong contig fasta file. Sorry about that. Maybe there could be some warning message about it if the bam files header is different from the -f fasta file sequences IDs.  Thanks again for the quick response.

**Comment by mourisl** [comment]
Sorry for the trouble. 
Rascaf already checks that the sequence IDs are the same from bam file header and the fasta file. I just added more tests to make sure the bam file are compatible with the fasta file.

**Comment by lijingbu** [comment]
Awesome! Thanks.
