### ISSUE TITLE
insufficient argument validation

### ISSUE THREAD

**Issue by pickettbd** [mourisl/Rascaf#13]
When running rascaf, if an option argument is empty string (e.g., '-b ""' or '-f ""') or missing (e.g., '-b -f somefile.fa', the program seg faults. Additional argument validation would be helpful.

**Comment by mourisl** [comment]
Thanks for the suggestion. I just added the tests to the existence of files specified by -b, -f, which is another way to make sure the arguments are correct.

**Comment by pickettbd** [comment]
Awesome! Thank you :)
