### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by pickettbd** [mourisl/Rascaf#15]
A simple addition to the README might be helpful. When I ran the sample test, it appeared to overwrite the original fasta file. Upon delving into the code, I realized that the parameter provided to rascaf-join with "-o" simply had ".fa" and ".info" appended to it to create the two output files. It just so happened that "-o sample/sample" will cause the original "sample/sample.fa" to be overwritten. I see nothing wrong with the approach, but it would be nice to have known what to expect from the README. It would be a bummer for someone to have their initial assembly fasta file lost forever by being overwritten.

**Comment by mourisl** [comment]
Thanks for so many good suggestions! It is definitely a disaster if rascaf overwrite the raw assembly file.
I just added a test in rascaf-join to throw an error if the output fasta file overwrite the input fasta file.

**Comment by pickettbd** [comment]
You're welcome! :) I downloaded the changes and tried it on the sample. That's a helpful fix- thank you!
