### ISSUE TITLE
Error running rascaf in TORQUE

### ISSUE THREAD

**Issue by Coayala** [mourisl/Rascaf#16]
Hello,

I need to run all my jobs in a scheduler, however when I try to run rascaf-join it gives me the following error:

Found raw assembly file: /panfs/panfs.cluster/scratch/ch1005/genomes/D_maidis_final.contigs.fa
Failed to resolve the path of file PBS_QUEUE=batch.

I don't know why it is trying to resolve the path of the scheduler queue.

Please can you help me with that?

**Comment by mourisl** [comment]
Can you show me the line start with “command line” in rascaf.out file?

**Comment by mourisl** [comment]
I think I've figured out the reason and updated the code. Could you please update rascaf and run it? You only need to run rascaf-join since the other parts are not changed.

**Comment by Coayala** [comment]
Hello, sorry for not answering earlier.

I updated it and ran it again but I get the same error

`Found raw assembly file: /panfs/panfs.cluster/scratch/ch1005/genomes/D_maidis_final.contigs.fa
Failed to resolve the path of file PBS_QUEUE=batch.`

This is the command that I am using

`${RASCAF_DIR}/rascaf-join -r rascaf_Dama.out -o rascaf_Dama_scaffold`

**Comment by mourisl** [comment]
Oh, I did not notice the "git push" was failed last time. It should be OK now. Can you give to another try? Sorry for the trouble.

**Comment by Coayala** [comment]
It is not any trouble. Now it is working. Thank you for all your help.
