### ISSUE TITLE
hpp:556: void Blocks::GetAlignmentsInfo(Alignments&): Assertion `readCnt > 30' failed. /job_scripts/3643772: line 33: 55796 Aborted (core dumped)

### ISSUE THREAD

**Issue by emmannaemeka** [mourisl/Rascaf#19]
hello, i also seem to have similar problem
Found 432405 exon blocks.
rascaf: blocks.hpp:556: void Blocks::GetAlignmentsInfo(Alignments&): Assertion `readCnt > 30' failed.
/job_scripts/3643772: line 33: 55796 Aborted (core dumped) ${RASCAF}/rascaf -b ${READS}/..unfilt_RNA.bam -f ${FASTA}/20190319.._001_001_1st_assembly_minION.ctn.fa -o ${TARGET}/rascaf_1st

SRR3453110.85720556	163	ctg1	18931	40	9M3I89M	=	18980	150 ATTTATGATAAAAAAAAAGAATTTAATAGATGGGCACACTACTAGGCACACTTATTCAAAGTAAATAAGATTTAGGAGCATATATGTATGAATTTCAATTA	?@BFFFFDHHHFHIJJGGFFFGIJIGGDHIGGGGHHGHIJJIJIJJIJGGGCHHHHEEHBDBDFCCDEEECED>CCDD?BDDDEEECCFEDDEDCACCDDD	AS:i:-24	XN:i:0	XM:i:2	XO:i:1	XG:i:3	NM:i:5	MD:Z:16C60C20	YS:i:-7 YT:Z:CP
SRR3453110.89338447	163	ctg1	18940	42	101M	=	18986	147 AAAAAAGAATTTAATAGATGGGCACACTACTAGGCACACTTATTCAAAGTAAATAAGATTTAGGAGCATATATGTATGAATTTCAATTAATTGAAACTGAG CCCFFFFFHHHHHJJJJJJJJJIJJJJJJJJJIJJJJJJJJJJJJJJJJGFHIJJJJIJJJJJJJJIGJHHHHHFHHFFFFFFFEEDEEDEEDDDDDCCCC	AS:i:-11	XN:i:0	XM:i:2	XO:i:0	XG:i:0	NM:i:2	MD:Z:7C60C32	YS:i:-5	YT:Z:CP
SRR3453110.90544994	163	ctg1	18960	42	101M	=	19116	256 GGCACACTACTAGGCACACTTATTCAAAGTAAATAAGATTTAGGAGCATATATGTATGAATTTCAATTAATTGAAACTGAGTTGGTATTTGGGTGATTTGT	@@@DFDFFHFFBFEGGIJJHIEHIHFEE>HHGGIGDCBFHGEIB4?D?DB??BDGHEGCEHHHGC=BFGFDHHGFC@EGCGHGFFCE?CBDBB=AA;A@@>	AS:i:-5	XN:i:0	XM:i:1 XO:i:0	XG:i:0	NM:i:1	MD:Z:48C52	YS:i:-8	YT:Z:CP
SRR3453110.89452103	99	ctg1	18970	42	101M	=	19010	141 TAGGCACACTTATTCAAAGTAAATAAGATTTAGGAGCATATATGTATGAATTTCAATTAATTGAAACTGAGTTGGTATTTGGGTGATTTGTCAGGATTGAA @@CFFFDFHGFFHGGHIIIFHIGGJGIHIEHIGGGHIIIHIIIGBHGEGEFHGHGHIIJIIGGGICJEE>HCHIIIHGIIGF@;A=EBCDEFFFA;AEEDD	AS:i:-6	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:38C62	YS:i:-4	YT:Z:CP
SRR3453110.85720556	83	ctg1	18980	40	101M	=	18931	-150 TATTCAAAGTAAATAAGATTTAGGAGCATATATGTATGAATTTCAATTAATTGAAACTGAGTTTGTATTTGGGTGATTTGTCAGGATTGAAGAGACCAAAA @3;CCEDEDFFDDFCFHHHHFFGGDDGCHEGIEJGGBCDIHGIIIGEHDFBGEGGHGFDHGFC*GJJJIGHFHFGIJJJHDJJIHIGIHHHHHDDFFF@@C	AS:i:-7	XN:i:0	XM:i:2	XO:i:0	XG:i:0	NM:i:2	MD:Z:28C34G3YS:i:-24 YT:Z:CP
SRR3453110.89338447	83	ctg1	18986	42	101M	=	18940	-147 AAGTAAATAAGATTTAGGAGCATATATGTATGAATTTCAATTAATTGAAACTGAGTTGGTATTTGGGTGATTTGTCAGGATTGAAGAGACCAAAATGTCGC CCDDEDDDCCEDEFEEDFEGGHHFFGIJJIIIIJJJJIJJJJJIJJJJIIIIJJJJIJJJJJJJJJJJJJJJJJJJJJJJJJJJJIHIFHHHHFFFFFCCC	AS:i:-5	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:22C78	YS:i:-11	YT:Z:CP
SRR3453110.74320311	99	ctg1	19002	42	101M	=	19034	132 GGAGCATATATGTATGAATTTCAATTAATTGAAACTGAGTTGGTATTTGGGTGATTTGTCAGGATTGAAGAGACCAAAATGTCGCTCAGTTTCGGCACCCT	@@@DFFDDDHFHCEGHD>DHGEHEHIIBGFEFCHIGE?EB@C@::CDGFHA?68?D?BFHIIC>FGGII@GGII;=@6ch?7=2;/?ACCDEDB:?==?BA	AS:i:-5	XN:i:0	XM:i:1 XO:i:0	XG:i:0	NM:i:1	MD:Z:6C94	YS:i:-8	YT:Z:CP
SRR3453110.89452103	147	ctg1	19010	42	101M	=	18970	-141 TATGTATGAATTTCAATTAATTGAAACTGAGTTGGTATTTGGGTGATTTGTCAGGGTTGAAGAGACCAAAATGTCGCTCAGTTTCGGCACCCTGTTTCTGG DDCDDEDCDCCCCCEEDDCA>FDEFCDDCDDDECECCA?;FHHEHEEHGGHIHB@=GGGGGGIGHGIJJJIIIIGJIEFJIIIIJIHFAFGHFFFFDD@@@	AS:i:-4	XN:i:0	XM:i:1	XO:i:0	XG:i:0	NM:i:1	MD:Z:55A45	YS:i:-6	YT:Z:CP
SRR3453110.74320311	147	ctg1	19034	42	77M1I23M	=	19002	-132 AACTGAGTTGGTATTTGGGTGATTTGTCAGGATTGAAGAGACCAAAATGTCGCTCAGTTTCGGCACCCTGTTTCTGGTTTTCGTCGAACATGGCAAACAAG	>:CCCC@>CCCAAABBB?@>@><>@ccccACCCAACCBBCDDCCD>A:>GGIHGGEGHGFB9IGBC@FIGGEGGBGDBGGGGFCCDFF??DDDBD??@	AS:i:-8	XN:i:0	XM:i:0	XO:i:1	XG:i:1	NM:i:1	MD:Z:100	YS:i:-5	YT:Z:CP
SRR3453110.84141312	99	ctg1	19042	42	69M1I31M	=	19116	174 TGGTATTTGGGTGATTTGTCAGGATTGAAGAGACCAAAATGTCGCTCAGTTTCGGCACCCTGTTTCTGGTTTTCGTCGAACATGGCAAACAAGAAGGTTTC B@CADDFFHHHFFHIJJJHIJJJIJIIJJIJJGIIJJJJIJHIJIJIFIIJIIIJJJIJJIHHHHHHFDBEFDECDBD??BDDCDDDDDDDDDCDDD?CDD	AS:i:-8	XN:i:0	XM:i:0	XO:i:1	XG:i:1	NM:i:1	MD:Z:100	YS:i:-8	YT:Z:CP

**Comment by mourisl** [comment]
It could be BAM file is not intact. For example, for the entry:
"SRR3453110.74320311 147 ctg1 19034 42 77M1I23M = 19002 -132 AACTGAGTTGGTATTTGGGTGATTTGTCAGGATTGAAGAGACCAAAATGTCGCTCAGTTTCGGCACCCTGTTTCTGGTTTTCGTCGAACATGGCAAACAAG >:CCCC@>CCCAAABBB?@>@><>@ccccACCCAACCBBCDDCCD>A:>GGIHGGEGHGFB9IGBC@FIGGEGGBGDBGGGGFCCDFF??DDDBD??@ AS:i:-8 XN:i:0 XM:i:0 XO:i:1 XG:i:1 NM:i:1 MD:Z:100 YS:i:-5 YT:Z:CP"
while the sequence has 101 bp, the quality score only has 98bp.
