### ISSUE TITLE
Base-level error rate is high in assembly. Suggestions?

### ISSUE THREAD

**Issue by chocotwig** [mourisl/Rascaf#20]
Hi, 
I'm trying to apply Rascaf to an assembly that is unpolished and has high base level errors. I still want to try out Rascaf, and I was wondering if there are parameters we could tune to accept higher mismatch rates.

Thanks!

**Comment by mourisl** [comment]
Rascaf relies on the aligners and did not use mismatch rates after getting the alignment. You can adjust the parameters in RNA-seq aligner such as tophat, star or hisat for them to align reads with more mismatches.

**Comment by chocotwig** [comment]
Thanks!
