### ISSUE TITLE
Rascaf-join failed

### ISSUE THREAD

**Issue by ctxchris** [mourisl/Rascaf#6]
Hi,

I mapped several RNAseq libraries to my reference genome using BWA mem and sorted the BAM file for coordinate with samtools sort (I checked that it is really is coordinate sorted).
I then executed Rascaf like this:

```
rascaf-wrapper.pl -b mapping.sorted.bam -f reference.fasta -o reference.consensus.rascaf
```

The log file contains the following:

>rascaf -b mapping.sorted.bam -o mapping.sorted_0 -f reference.fasta -o reference.rascaf
Found 8273702 exon blocks.
Found 4555833 gene blocks.
Found 58394 non-trivial gene block components.
rascaf-join  -r reference.sorted_0.out -o reference.rascaf
rascaf-join failed.

The file reference.rascaf.out start with 

>Contigs
0: Consensus_utg000001l 1 23842
1: Consensus_utg000002l 1 28081
...

and continues with a lot of entries like these:

> Contig 105247 is misassembled. (Consensus_utg105248l 1-20821): (7197-7854) (5169-6053): Found deletion between.

> 3: (Consensus_utg000005l 45898 4 -) (Consensus_utg059814l 54357 59813 +) (Consensus_utg025230l 58213 25229 -) 

> WARNINGS:
71: (Consensus_utg044293l:12054-12178 44292 +) (Consensus_utg050357l:31186-33007 50356 +)

Do you have an idea what could have been gone wrong?
Chris

**Comment by ctxchris** [comment]
It worked when I exectued rascaf-wrapper and rascaf-join manually.

**Comment by mourisl** [comment]
Thanks for letting me know! It seems the rascaf-wrapper parsed the argument wrong. I will fix it soon.

**Comment by mourisl** [comment]
It should be fixed now. Thanks!
