### ISSUE TITLE
rascaf-join not running

### ISSUE THREAD

**Issue by kapr0001** [mourisl/Rascaf#8]
Hai, 

I am working to improve my draft genome assembly with PE-RNA sequences. I was able to scaffold my data with 
`./rascaf -b *.bam -f assm1kb.fa -o outtestfile. `

I have problem with rascaf-join (command below)
`./rascaf-join -r outtestfile -o assembly_scaftest   `

after i submit this command nothing happens, just remains forever as 
_Found raw assembly file: ../../../*-sort.bam_ 

I have also run the sample data to check if rascaf-join, i still have the same issue 

> Found raw assembly file: omitopsis/rna_geno/rascaf/sample/sample-sort.bam
(remains forever without any further error or output). i have read the previous queries, that was suggested to sort out *bam file, i have tired it but still with no progress. 

could you please help me with the issue?

thank you 
Prakash

**Comment by mourisl** [comment]
Rascaf does not support wildcard ("*") in file name. To run multiple files, you have to run rascaf on each file separately, and the rascaf-join the output files. As in the readme file, if you have two bam files A.bam, B.bam, the way to run rascaf should be:
>./rascaf -b A.bam -f assembly.fa -o A
>./rascaf -b B.bam -f assembly.fa -o B
>./rascaf-join -r A.out -r B.out -o assembly_scaffold

The other way is to run rascaf is to use rascaf-wrapper.pl, it does not support wildcard as well, and you can run it by: 
>perl ./rascaf-wrapper.pl -b A.bam,B.bam -f assm1kb.fa -o assembly_scaftest
And the output should be in assembly_scaftest.fa. 

Please let me know whether this works.

Li

**Comment by kapr0001** [comment]
Hi Li, 

Thank you for quick response.   sorry for the wildcard mentioning (*). there is no any wildcard in my command. I have no issues with ./rascaf, but only with ./rascaf-join.

after executing rascaf-join command, i get an info  

> Found raw assembly file: ../../../name_sort.bam and it stays forever. (its same problem with sample file as well)

after submitting as job script i got this error. 

> Segmentation fault (core dumped). someone had this issues too, i haven't seen any answers to this question so i am posting it again. 

/Prakash

**Comment by mourisl** [comment]
I just noticed that the sample data sets also failed on your computer, can you show me the exact command you use on the sample data set?

I also uploaded a new join.cpp that can output more information, that may tell rascaf-join failed at which stage. 

Li

**Comment by kapr0001** [comment]
here is the codes that i have used for sample data. 
I start working with  rascaf-wrapper.pl. will let you know how it works.

code for scaffolding 
` ./rascaf -b sample/sample.bam -f sample/sample.fa`

sample data command for rascaf-join 
`./rascaf-join -r sample.out -o sample2`

after i submit the rascaf-join, it finds the bam file, there is no any progress later 

> Found raw assembly file: omitopsis/rna_geno/rascaf/sample/sample.bam 

thank you 
prakash

**Comment by kapr0001** [comment]
Hi again, 

both the commands worked out now. it was issue with our grid engine. but i works fine in my local machine. 

one more question, is there way to find the stats of the improved assembly in rascaf?

thank you 
prakash

**Comment by mourisl** [comment]
Glad it works out. There are various stats can be evaluated, so we don't have such program in rascaf package. As far as I know, BUSCO is a good choice if you want to look at stats other than N50.
